# Generated by Django 4.1 on 2023-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mashup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singername', models.CharField(max_length=1000)),
                ('n_videos', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
